name: Deploy to EC2 using AWS CLI

on:
  push:
    branches:
      - "main"

jobs:
  deploy-master:
    name: Deploy to EC2 (Prod)
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 1.5 :) Build pip package
      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Build Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel build

      - name: Build AIModels Package and Copy to Other Folders
        working-directory: AIModels
        run: |
             python -m build
             PACKAGE_PATH=$(ls dist/*.whl)
             cp $PACKAGE_PATH ../PredictionService/
        shell: bash


      # Step 2: Configure AWS CLI
      - name: Configure AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AMAZON_S3_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AMAZON_S3_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AMAZON_S3_REGION_NAME }}

      # Step 3: Ensure EC2 Instance is Running
      - name: Start EC2 if stopped and wait until running
        run: |
          INSTANCE_ID="i-02a859aacad892fd3"

          # Get the instance state correctly
          STATUS=$(aws ec2 describe-instances --instance-ids $INSTANCE_ID --query "Reservations[0].Instances[0].State.Name" --output text)

          echo "EC2 Instance Status: $STATUS"

          if [ "$STATUS" == "stopped" ]; then
            echo "Starting EC2 instance $INSTANCE_ID..."
            aws ec2 start-instances --instance-ids $INSTANCE_ID

            echo "Waiting for instance to be running..."
            aws ec2 wait instance-running --instance-ids $INSTANCE_ID

            echo "EC2 instance is now running."
          elif [ "$STATUS" == "pending" ]; then
            echo "Instance is in pending state. Waiting for it to be running..."
            aws ec2 wait instance-running --instance-ids $INSTANCE_ID
            echo "EC2 instance is now running."
          else
            echo "EC2 instance is already in state: $STATUS."
          fi



      # Step 3: Build and Push Docker Image to ECR
      - name: Build and Push Docker Image to ECR
        run: |
          # Log in to ECR
          aws ecr get-login-password --region ${{ secrets.AMAZON_S3_REGION_NAME }} | docker login --username AWS --password-stdin ${{ secrets.ECR_URI }}
         
          # Go to the PredictionService directory
          cd PredictionService

          # Build Docker image
          docker build -t diagnostic-ai:latest .

          # Tag the image
          docker tag diagnostic-ai:latest ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AMAZON_S3_REGION_NAME }}.amazonaws.com/diagnostic-ai:latest

          # Push the Docker image to ECR
          docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AMAZON_S3_REGION_NAME }}.amazonaws.com/diagnostic-ai:latest


      # Step 5: Upload docker-compose.yml to S3
      - name: Upload docker-compose.yml to S3
        run: |
          aws s3 cp PredictionService/docker-compose.yml s3://${{ secrets.S3_BUCKET_NAME }}/docker-compose.yml --region ${{ secrets.AMAZON_S3_REGION_NAME }}
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AMAZON_S3_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AMAZON_S3_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AMAZON_S3_REGION_NAME }}



      # Step 5: Upload docker-compose.yml to S3
      - name: Upload docker-compose.yml to S3
        run: |
          aws s3 cp docker-compose.yml s3://${{ secrets.S3_BUCKET_NAME }}/docker-compose.yml --region ${{ secrets.AMAZON_S3_REGION_NAME }}
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AMAZON_S3_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AMAZON_S3_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AMAZON_S3_REGION_NAME }}

      # Step 5: Deploy Docker on EC2 via SSM
      - name: Deploy Docker on EC2 via SSM
        run: |
          # Assign GitHub secrets to shell variables
          S3_BUCKET_NAME=${{ secrets.S3_BUCKET_NAME }}
          REGION=${{ secrets.AMAZON_S3_REGION_NAME }}
          ECR_URI=${{ secrets.ECR_URI }}
          AWS_ACCOUNT_ID=${{ secrets.AWS_ACCOUNT_ID }}
          INSTANCE_ID=i-02a859aacad892fd3

          # Send the SSM command
          COMMAND_ID=$(aws ssm send-command \
            --document-name "AWS-RunShellScript" \
            --targets "Key=instanceIds,Values=${INSTANCE_ID}" \
            --parameters "commands=[
              'set -e',

              'echo Downloading the docker-compose.yml from S3...',
              'aws s3 cp s3://${S3_BUCKET_NAME}/docker-compose.yml /home/ubuntu/docker-compose.yml --region ${REGION}',

              'echo Stopping and removing old Docker containers...',
              'docker-compose -f /home/ubuntu/docker-compose.yml down',

              'echo Logging into ECR...',
              'aws ecr get-login-password --region ${REGION} | docker login --username AWS --password-stdin ${ECR_URI}',

              'echo Pulling the new Docker image...',
              'docker pull ${AWS_ACCOUNT_ID}.dkr.ecr.${REGION}.amazonaws.com/diagnostic-ai:latest',

              'echo Starting the containers with new image...',
              'docker-compose -f /home/ubuntu/docker-compose.yml up -d',

              'echo Cleaning up unused images...',
              'docker system prune -f || true',

              'echo Deployment complete!'
            ]" \
            --comment "Deploying new Docker image to EC2" \
            --region "$REGION" \
            --query "Command.CommandId" --output text)

          echo "SSM Command ID: $COMMAND_ID"

          # Wait for the command to complete
          while true; do
            STATUS=$(aws ssm get-command-invocation \
              --command-id $COMMAND_ID \
              --instance-id $INSTANCE_ID \
              --region $REGION \
              --query "Status" --output text)

            echo "Current Status: $STATUS"

            if [ "$STATUS" = "Success" ]; then
              echo "SSM Command completed successfully!"
              break
            elif [ "$STATUS" = "Failed" ] || [ "$STATUS" = "Cancelled" ]; then
              echo "SSM Command failed or was cancelled."
              echo "Fetching command output..."
              aws ssm get-command-invocation \
                --command-id $COMMAND_ID \
                --instance-id $INSTANCE_ID \
                --region $REGION \
                --query "StandardErrorContent" \
                --output text

              echo "Fetching standard output..."
              aws ssm get-command-invocation \
                --command-id $COMMAND_ID \
                --instance-id $INSTANCE_ID \
                --region $REGION \
                --query "StandardOutputContent" \
                --output text
              exit 1
            else
              sleep 10
            fi
          done

  #stop-ec2:
  #  name: Stop EC2 If Running
  #  runs-on: ubuntu-latest
  #  needs: deploy-master  # Ensure this job runs after deployment
  #  if: always()
  #
  #  steps:
  #    - name: Configure AWS CLI
  #      uses: aws-actions/configure-aws-credentials@v1
  #      with:
  #        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
  #        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  #        aws-region: ${{ secrets.AWS_REGION }}
  #
  #    - name: Stop EC2 If Running
  #      run: |
  #        INSTANCE_ID="i-043c8050d6c02f6b4"
  #        STATUS=$(aws ec2 describe-instances --instance-ids $INSTANCE_ID --query "Reservations[0].Instances[0].State.Name" --output text)
  #
  #        echo "EC2 Instance Status: $STATUS"
  #
  #        if [ "$STATUS" == "running" ]; then
  #          echo "Stopping EC2 instance $INSTANCE_ID..."
  #          aws ec2 stop-instances --instance-ids $INSTANCE_ID
  #          aws ec2 wait instance-stopped --instance-ids $INSTANCE_ID
  #          echo "EC2 instance is now stopped."
  #        else
  #          echo "EC2 instance is already in state: $STATUS."
  #        fi