name: Deploy to EC2 using AWS CLI

on:
  push:
    branches:
      - "main"
      - "rollback"

jobs:
  build-and-deploy:
    name: Build & Deploy Services
    runs-on: ubuntu-latest

    strategy:
      matrix:
        service:
          - genai-app
          - microscopy

    env:
      REGION: ${{ secrets.AMAZON_S3_REGION_NAME }}
      ECR_URI: ${{ secrets.ECR_URI }}
      AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
      S3_BUCKET_NAME: ${{ secrets.S3_BUCKET_NAME }}
      INSTANCE_ID: i-07a7ff0d0e44e03c5
      IMAGE_TAG: v100   # put your desired image tag here

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Build Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel build

      - name: Build AIModels Package and Copy to Other Folders
        working-directory: AIModels
        run: |
          python -m build
          PACKAGE_PATH=$(ls dist/*.whl)
          cp $PACKAGE_PATH ../PredictionService/
        shell: bash

      - name: Configure AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AMAZON_S3_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AMAZON_S3_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AMAZON_S3_REGION_NAME }}
      
      - name: Copy .whl file from s3
        run: |  
          aws s3 cp s3://praid-ai/maanz_medical_ai_models-1.0.0-py3-none-any.whl MicroscopyService/maanz_medical_ai_models-1.0.0-py3-none-any.whl --region ap-south-1
          aws s3 cp s3://praid-ai/maanz_medical_ai_models-1.0.0-py3-none-any.whl GenAIService/backend/maanz_medical_ai_models-1.0.0-py3-none-any.whl --region ap-south-1

      - name: Build and Push Docker Image to ECR
        run: |
          aws ecr get-login-password --region $REGION | docker login --username AWS --password-stdin $ECR_URI

          if [ "${{ matrix.service }}" = "genai-app" ]; then
            cd GenAIService/backend/
          else
            cd MicroscopyService/
          fi

          docker build -t ${{ matrix.service }}:${{ env.IMAGE_TAG }} .
          docker tag ${{ matrix.service }}:${{ env.IMAGE_TAG }} $AWS_ACCOUNT_ID.dkr.ecr.$REGION.amazonaws.com/${{ matrix.service }}:${{ env.IMAGE_TAG }}
          docker push $AWS_ACCOUNT_ID.dkr.ecr.$REGION.amazonaws.com/${{ matrix.service }}:${{ env.IMAGE_TAG }}

      # Update docker-stack.yml with the new tag
      - name: Update docker-stack.yml with dynamic tag
        run: |
          if [ "${{ matrix.service }}" = "genai-app" ]; then
            cd GenAIService/backend/
          else
            cd MicroscopyService/
          fi
          
          sed -i "s|\(image: .*/diagnostic-ai:\).*|\1${{ env.IMAGE_TAG }}|" docker-stack.yml
          sed -i "s|\(image: .*/microscopy:\).*|\1${{ env.IMAGE_TAG }}|" docker-stack.yml

      - name: Upload docker-stack.yml to S3
        run: |
          if [ "${{ matrix.service }}" = "genai-app" ]; then
            aws s3 cp GenAIService/backend/docker-stack.yml s3://$S3_BUCKET_NAME/genai-app/docker-stack.yml --region $REGION
          else
            aws s3 cp MicroscopyService/docker-stack.yml s3://$S3_BUCKET_NAME/microscopy/docker-stack.yml --region $REGION
          fi

      - name: Deploy Both Services via SSM
        run: |
          COMMAND_ID=$(aws ssm send-command \
            --document-name "AWS-RunShellScript" \
            --targets "Key=instanceIds,Values=${INSTANCE_ID}" \
            --parameters "commands=[
              'set -e',
              'echo Enabling Docker Swarm...',
              'docker swarm init || echo Already initialized',

              'mkdir -p /home/ubuntu/genai-app',
              'mkdir -p /home/ubuntu/microscopy',

              'echo Downloading docker-stack.yml files from S3...',
              'aws s3 cp s3://${S3_BUCKET_NAME}/genai-app/docker-stack.yml /home/ubuntu/genai-app/docker-stack.yml --region ${REGION}',
              'aws s3 cp s3://${S3_BUCKET_NAME}/microscopy/docker-stack.yml /home/ubuntu/microscopy/docker-stack.yml --region ${REGION}',

              'echo Logging into ECR...',
              'aws ecr get-login-password --region ${REGION} | docker login --username AWS --password-stdin ${ECR_URI}',

              'echo Deploying genai-app...',
              'docker stack deploy -c /home/ubuntu/genai-app/docker-stack.yml --with-registry-auth genaiapp',

              'echo Deploying microscopy...',
              'docker stack deploy -c /home/ubuntu/microscopy/docker-stack.yml --with-registry-auth microscopy',

              'echo Deployment of both services complete!'
            ]" \
            --comment "Deploy both stacks to EC2 using Docker Swarm" \
            --region "$REGION" \
            --query "Command.CommandId" --output text)

          echo "SSM Command ID: $COMMAND_ID"

          # Wait for command to finish
          while true; do
            STATUS=$(aws ssm get-command-invocation \
              --command-id $COMMAND_ID \
              --instance-id $INSTANCE_ID \
              --region $REGION \
              --query "Status" --output text)

            echo "Current Status: $STATUS"
            if [ "$STATUS" = "Success" ]; then
              echo "Deployment successful for both services"
              break
            elif [ "$STATUS" = "Failed" ] || [ "$STATUS" = "Cancelled" ]; then
              echo "SSM command failed or was cancelled"
              aws ssm get-command-invocation \
                --command-id $COMMAND_ID \
                --instance-id $INSTANCE_ID \
                --region $REGION \
                --query "StandardErrorContent" --output text
              exit 1
            else
              sleep 10
            fi
          done


  #stop-ec2:
  #  name: Stop EC2 If Running
  #  runs-on: ubuntu-latest
  #  needs: deploy-master  # Ensure this job runs after deployment
  #  if: always()
  #
  #  steps:
  #    - name: Configure AWS CLI
  #      uses: aws-actions/configure-aws-credentials@v1
  #      with:
  #        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
  #        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  #        aws-region: ${{ secrets.AWS_REGION }}
  #
  #    - name: Stop EC2 If Running
  #      run: |
  #        INSTANCE_ID="i-043c8050d6c02f6b4"
  #        STATUS=$(aws ec2 describe-instances --instance-ids $INSTANCE_ID --query "Reservations[0].Instances[0].State.Name" --output text)
  #
  #        echo "EC2 Instance Status: $STATUS"
  #
  #        if [ "$STATUS" == "running" ]; then
  #          echo "Stopping EC2 instance $INSTANCE_ID..."
  #          aws ec2 stop-instances --instance-ids $INSTANCE_ID
  #          aws ec2 wait instance-stopped --instance-ids $INSTANCE_ID
  #          echo "EC2 instance is now stopped."
  #        else
  #          echo "EC2 instance is already in state: $STATUS."
  #        fi